# Hecto Car Classification Configuration

# Data Settings
data:
  root_dir: "data"
  train_dir: "data/train"
  test_dir: "data/test"
  test_csv: "data/test.csv"
  submission_csv: "data/sample_submission.csv"
  num_classes: 396

# Model Settings
model:
  backbone: "convnext_base"
  pretrained: true
  pool_type: "gem"
  gem_p: 3.0
  head_type: "subcenter_arcface"
  num_subcenters: 3
  scale_factor: 30.0
  
# Training Settings
training:
  seed: 42
  num_folds: 5
  epochs: 20
  batch_size: 32
  num_workers: 4
  device: "cuda"
  amp: true  # Automatic Mixed Precision
  gradient_accumulation: 1
  
# Optimizer Settings
optimizer:
  type: "adamw"
  base_lr: 3.0e-4
  head_lr_multiplier: 10
  weight_decay: 1.0e-2
  betas: [0.9, 0.999]
  
# Scheduler Settings
scheduler:
  type: "cosine"
  warmup_epochs: 3
  min_lr: 1.0e-6
  
# Augmentation Settings
augmentation:
  image_size: 448
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  
  train:
    random_resized_crop:
      scale: [0.6, 1.0]
      ratio: [0.75, 1.333]
    color_jitter:
      brightness: 0.4
      contrast: 0.4
      saturation: 0.4
      hue: 0.1
      p: 0.5
    shift_scale_rotate:
      shift_limit: 0.05
      scale_limit: 0.1
      rotate_limit: 15
      p: 0.5
    horizontal_flip:
      p: 0.5
    coarse_dropout:
      max_height: 112  # 25% of 448
      max_width: 112
      min_height: 45   # 10% of 448
      min_width: 45
      max_holes: 1
      min_holes: 1
      p: 0.3
  
  val:
    resize:
      height: 448
      width: 448

# CutMix Settings
cutmix:
  alpha: 1.0
  prob: 0.5

# EMA Settings
ema:
  enabled: true
  decay: 0.999
  
# Logging Settings
logging:
  save_dir: "models"
  log_interval: 50
  save_best_only: true
  save_last: true
  
# Inference Settings
inference:
  batch_size: 64
  tta: false  # Test Time Augmentation
  ensemble: true
  
# Special Class Mapping
special_classes:
  - ["K5_3세대_하이브리드_2020_2022", "K5_하이브리드_3세대_2020_2023"]
  - ["디_올뉴니로_2022_2025", "디_올_뉴_니로_2022_2025"]
  - ["718_박스터_2017_2024", "박스터_718_2017_2024"]
  - ["RAV4_2016_2018", "라브4_4세대_2013_2018"]
  - ["RAV4_5세대_2019_2024", "라브4_5세대_2019_2024"]